branches:
    only:
        - master

language: node_js

sudo: required

node_js:
    - '8'


before_install:
    - sh install.sh

install:
    - npm install
    
script:
    - ls -l
    - cd ./blog
    - ls -l
    - hexo clean
    - hexo generate
    - mv ./public blog
    - echo '结束'

