branches:
    only:
        - master

language: node_js

node_js:
    - '10'

cache: npm

sudo: false

before_script:
    - sh install.sh
    
script:
    - echo '进入blog目录'
    - ls -l ./node_modules
    - cd ./blog
    - ../node_modules/hexo-cli/bin/hexo clean
    - ../node_modules/hexo-cli/bin/hexo generate
    - mv ./public blog
    - ls -l ./blog
    - echo '结束'

