branches:
    only:
        - master

language: node_js

node_js:
    - '10'

cache:
    directories:
        - node_modules

sudo: false

before_script:
    - npm install hexo-cli -g
script:
    - cd ./blog
    - hexo clean
    - hexo generate
    - mv ./public blog
    - ll ./blog

