branches:
    only:
        - master

language: node_js


node_js:
    - '8'

cache:
    directories:
        - node_modules

before_install:
    - sh install.sh

install:
    - cd ./blog
    - npm install

script:
    - ls -l
    - cd ./blog
    - ls -l
    - hexo clean
    - hexo generate
    - git config user.name 'Foxdaxian'
    - git config user.email '945039036@qq.com'
    - hexo deploy
    - echo '结束'
