branches:
    only:
        - master

language: node_js

node_js:
    - '8'


before_script:
    - sh install.sh
    
script:
    - ls -l
    - hexo-cli clean
    - hexo-cli generate
    - mv ./public blog
    - ls -l ./blog
    - echo '结束'

