branches:
    only:
        - master

language: node_js

node_js:
    - '10'

cache: npm

sudo: false

before_script:
    - npm install hexo-cli -g
    
script:
    - ls -l
    - cd ./blog
    - hexo clean
    - hexo generate
    - mv ./public blog
    - ls -l ./blog

