branches:
    only:
        - master

language: node_js

node_js:
    - '10'

cache:
    directories:
        - node_modules

sudo: false

before_script:
    - sh install.sh
script:
    - sh deploy.sh
