branches:
    only:
        - master

language: node_js

node_js:
    - '10'

sudo: false

before_script:
    - sh install.sh
    
script:
    - echo '进入blog目录'
    - ls -l
    - cd ./blog
    - hexo clean
    - hexo generate
    - mv ./public blog
    - ls -l ./blog
    - echo '结束'

