branches:
    only:
        - master

language: node_js

sudo: required

node_js:
    - '8'

cache:
    directories:
        - node_modules

before_install:
    - sh install.sh

install:
    - cd ./blog
    - npm install

script:
    - sh deploy.sh
